In [1]:
import os
path = "/dss/dsshome1/04/ge57san2/Conditional-Sig-Wasserstein-GANs"
os.chdir(path)
!git -C /dss/dsshome1/04/ge57san2/Conditional-Sig-Wasserstein-GANs pull  # pull from Github after having it initially cloned
import sys
sys.path.append('/dss/dsshome1/04/ge57san2/liao_requirements')
#!pip install --target=/dss/dsshome1/04/ge57san2/liao_requirements -r Requirement_files/ColabRequirements.txt

remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 10 (delta 8), reused 7 (delta 5), pack-reused 0 (from 0)
Unpacking objects: 100% (10/10), 878 bytes | 12.00 KiB/s, done.
From https://github.com/killivion/Conditional-Sig-Wasserstein-GANs
   cc9c9cc..a2b554f  master     -> origin/master
Updating cc9c9cc..a2b554f
Fast-forward
 TD3/portfolio_env.py | 12 ++----------
 lib/data.py          |  5 +++--
 2 files changed, 5 insertions(+), 12 deletions(-)


In [2]:
%run generate.py -spec mu=[0.06]_sigma=[[0.2]]_q=10 -test_length 1000 -sig_p 3 -sig_q 10 -dataset correlated_Blackscholes  
#ticker=^GSPC_start=2000-01-01_end=2025-01-01_q=10

Sampling:   0%|          | 0/1000 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/torch/storage.py:505: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.lo

1 3
tensor([[[ 0.6067],
         [-1.1730],
         [ 0.5656]]], device='cuda:0')
torch.Size([1, 3, 1])
10


Sampling:   1%|          | 12/1000 [00:00<00:32, 30.37it/s]

1 3
tensor([[[-0.9710],
         [ 0.5794],
         [ 1.8731]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3126],
         [ 0.8362],
         [ 0.1902]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.1920],
         [-0.2404],
         [ 1.0372]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5985],
         [ 0.3898],
         [-1.4126]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6130],
         [ 1.1115],
         [-0.0304]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2811],
         [-0.3495],
         [-0.4264]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1791],
         [ 0.2555],
         [-1.3337]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-6.6375e-05],
         [ 5.3938e-01],
         [-2.0858e-01]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9284],
         [ 0.5215],
         [ 0.3381]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1

Sampling:   3%|▎         | 34/1000 [00:00<00:14, 66.45it/s]

1 3
tensor([[[0.6706],
         [1.5562],
         [1.6181]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2779],
         [-0.0307],
         [ 1.0232]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3445],
         [ 1.3162],
         [-0.4596]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.6181],
         [-1.6762],
         [-0.5774]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5173],
         [ 0.5664],
         [-0.3242]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.1192],
         [-0.2601],
         [-0.9608]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.0273],
         [-0.6822],
         [ 1.4264]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.8965],
         [ 1.9915],
         [-1.0851]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6502],
         [ 0.4180],
         [-1.7666]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.1030],
       

Sampling:   6%|▌         | 55/1000 [00:00<00:11, 83.54it/s]

1 3
tensor([[[-0.8783],
         [ 0.8525],
         [ 0.6438]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.2385],
         [ 0.7619],
         [-1.4380]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.7218],
         [0.0257],
         [0.6558]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0182],
         [ 1.1926],
         [ 1.6143]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6392],
         [-0.4564],
         [ 0.4142]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.3254],
         [ 0.0542],
         [ 0.3225]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.8831],
         [-0.0533],
         [ 0.4505]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-2.0553],
         [ 1.0273],
         [-0.6822]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4333],
         [-0.9401],
         [-0.5508]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7486],
       

Sampling:   8%|▊         | 76/1000 [00:01<00:10, 91.82it/s]

1 3
tensor([[[-1.1863],
         [ 0.6566],
         [ 0.3152]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.6249],
         [-1.0518],
         [-0.3879]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2142],
         [-0.4374],
         [-1.9525]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1076],
         [ 2.3118],
         [-0.1743]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[1.0460],
         [1.6164],
         [0.3496]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.8987],
         [-0.6240],
         [-0.6130]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.0683],
         [0.3499],
         [1.1117]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.8145],
         [ 1.7445],
         [ 0.8970]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4478],
         [ 1.0623],
         [ 1.4397]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2653],
         [

Sampling:  10%|▉         | 98/1000 [00:01<00:09, 98.10it/s]

1 3
tensor([[[ 0.7274],
         [-0.5375],
         [ 0.5261]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.5723],
         [-0.5877],
         [ 0.5836]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2348],
         [ 0.7250],
         [ 0.3289]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5794],
         [-0.8328],
         [ 2.1723]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.5436],
         [-1.8266],
         [-0.6618]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.5479],
         [-0.5144],
         [-1.9199]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.8145],
         [-1.5074],
         [-1.2713]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3126],
         [-0.3989],
         [-0.9153]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.1245],
         [-0.1996],
         [ 0.2117]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.8362],
    

Sampling:  12%|█▏        | 120/1000 [00:01<00:08, 100.18it/s]

1 3
tensor([[[0.0447],
         [0.0491],
         [0.7187]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9959],
         [ 0.1192],
         [-0.2601]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2431],
         [-0.6340],
         [ 0.6109]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0140],
         [ 1.9512],
         [-1.6899]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2588],
         [ 1.3733],
         [ 0.0241]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.1196],
         [ 0.4366],
         [-1.2799]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2574],
         [-1.3621],
         [ 0.8689]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7351],
         [-1.5108],
         [ 2.3168]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7712],
         [-0.1304],
         [ 0.0991]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1890],
       

Sampling:  14%|█▍        | 142/1000 [00:01<00:08, 103.05it/s]

1 3
tensor([[[0.0284],
         [1.1287],
         [0.1206]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.8480],
         [ 0.0428],
         [-0.8424]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3039],
         [-0.9020],
         [-1.1037]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.5723],
         [-0.5877],
         [ 0.5836]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2891],
         [-0.6982],
         [ 0.9395]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7717],
         [ 0.1066],
         [ 0.8931]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6936],
         [ 0.0459],
         [-1.0406]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2537],
         [ 0.8039],
         [-0.3750]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.5779],
         [ 0.9550],
         [-1.5850]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.1864],
       

Sampling:  16%|█▋        | 164/1000 [00:01<00:08, 103.71it/s]

tensor([[[-0.7433],
         [-1.2620],
         [ 0.5797]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.5106],
         [-1.4937],
         [-0.1127]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.2568],
         [-0.3053],
         [ 0.0942]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.1262],
         [-0.6846],
         [ 0.5812]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.4920],
         [ 1.7490],
         [-0.1360]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5496],
         [-0.1275],
         [-0.9121]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.4688],
         [-0.2441],
         [-1.5234]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.3295],
         [ 0.9257],
         [ 0.3695]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.4638],
         [ 0.6706],
         [ 1.5562]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.1823],
        

Sampling:  19%|█▊        | 186/1000 [00:02<00:07, 104.93it/s]

1 3
tensor([[[-0.4073],
         [-1.0817],
         [-2.2161]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1743],
         [ 0.6746],
         [-0.9722]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5087],
         [-2.4704],
         [-0.4971]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1371],
         [-1.4584],
         [ 1.2057]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.3388],
         [ 0.6957],
         [-0.2624]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.1419],
         [-0.5294],
         [ 0.8067]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.4021],
         [-1.2305],
         [ 1.9187]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.6380],
         [-1.2410],
         [ 0.9841]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3750],
         [ 2.4163],
         [ 0.0146]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.8335],
    

Sampling:  21%|██        | 208/1000 [00:02<00:07, 104.84it/s]

1 3
tensor([[[-0.4009],
         [ 0.0766],
         [ 1.1807]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.3388],
         [ 0.6957],
         [-0.2624]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.7264],
         [0.4884],
         [1.7633]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.8588],
         [-0.0333],
         [ 0.5876]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3750],
         [ 2.4163],
         [ 0.0146]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[1.3676],
         [1.1268],
         [0.2774]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.1066],
         [0.8931],
         [0.3408]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.1861],
         [ 0.0276],
         [-0.0182]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.2133],
         [-1.6614],
         [ 0.5687]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.5746],
         [0.06

Sampling:  23%|██▎       | 230/1000 [00:02<00:07, 105.42it/s]

1 3
tensor([[[ 0.3261],
         [ 1.2184],
         [-0.3657]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.8145],
         [-1.5074],
         [-1.2713]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0549],
         [ 1.8484],
         [-1.2459]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9757],
         [-1.3587],
         [ 0.7609]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5743],
         [-0.5452],
         [-0.0388]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.5656],
         [-0.6392],
         [-0.4564]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.3739],
         [ 1.2857],
         [ 1.6197]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.5562],
         [ 1.6181],
         [-1.6762]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3039],
         [-0.9020],
         [-1.1037]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.2821],
    

Sampling:  25%|██▌       | 252/1000 [00:02<00:07, 103.11it/s]

tensor([[[-0.3029],
         [-0.5502],
         [ 0.7837]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.8289],
         [-1.3106],
         [-0.4616]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[2.3089],
         [0.9029],
         [0.7669]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7177],
         [-0.1500],
         [-0.3314]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.8783],
         [ 0.8525],
         [ 0.6438]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.4480],
         [ 0.6938],
         [-0.4925]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6505],
         [-0.6783],
         [ 1.5479]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.2410],
         [ 0.9841],
         [-0.8533]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3933],
         [ 0.8053],
         [-0.8852]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.7633],
         [ 

Sampling:  27%|██▋       | 274/1000 [00:03<00:06, 103.97it/s]

1 3
tensor([[[-0.5087],
         [-2.4704],
         [-0.4971]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.4364],
         [ 0.5910],
         [ 1.4709]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.4584],
         [ 1.2057],
         [ 1.4358]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.2932],
         [-1.6858],
         [-0.2804]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6042],
         [-1.2861],
         [ 1.5504]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4527],
         [ 0.3419],
         [-0.0962]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7443],
         [ 0.5491],
         [ 0.1820]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.8120],
         [ 1.4993],
         [ 0.7218]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3736],
         [-0.4527],
         [ 0.3419]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.7962],
     

Sampling:  30%|██▉       | 296/1000 [00:03<00:06, 104.12it/s]

1 3
tensor([[[1.0709],
         [0.9596],
         [0.2225]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.4584],
         [ 1.2057],
         [ 1.4358]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.9024],
         [ 1.5697],
         [-1.1943]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.0276],
         [-0.0182],
         [ 1.1926]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9092],
         [-0.8153],
         [ 0.1431]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.6202],
         [-0.9289],
         [-0.4049]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.0526],
         [-1.2465],
         [-0.6241]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3766],
         [ 0.9552],
         [-0.5051]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.8810],
         [ 0.1127],
         [ 1.5952]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2537],
       

Sampling:  32%|███▏      | 318/1000 [00:03<00:06, 103.93it/s]

1 3
tensor([[[-1.1382],
         [ 1.5477],
         [-0.2941]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2431],
         [-0.6340],
         [ 0.6109]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.6899],
         [-0.7970],
         [ 0.8503]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.2754],
         [ 0.8243],
         [-0.2443]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9722],
         [-1.2385],
         [ 0.7619]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.1201],
         [ 0.2304],
         [-1.7855]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7741],
         [-0.4468],
         [-0.1948]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3988],
         [ 1.9301],
         [-0.4777]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5724],
         [ 0.0968],
         [ 0.8778]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.7072],
    

Sampling:  34%|███▍      | 340/1000 [00:03<00:06, 104.78it/s]

1 3
tensor([[[-0.8951],
         [-1.5306],
         [ 0.3093]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.0805],
         [-0.9060],
         [-1.0441]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3408],
         [-0.3116],
         [-0.1119]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3879],
         [ 0.7195],
         [ 0.2778]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.4180],
         [-1.7666],
         [-1.9562]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0689],
         [-0.5547],
         [-2.0424]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.6641],
         [-0.4630],
         [ 0.1459]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0300],
         [ 1.0861],
         [ 0.9066]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.5741],
         [ 0.6011],
         [ 0.7389]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.0406],
    

Sampling:  36%|███▌      | 362/1000 [00:03<00:06, 105.38it/s]

1 3
tensor([[[-0.9959],
         [ 0.1192],
         [-0.2601]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5308],
         [-0.5467],
         [ 1.2137]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.8673],
         [0.9024],
         [1.5697]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.5571],
         [ 1.1964],
         [-1.6928]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7443],
         [ 0.5491],
         [ 0.1820]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7697],
         [-0.5661],
         [ 1.3133]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1384],
         [ 0.3378],
         [ 0.7486]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[1.4993],
         [0.5293],
         [1.1122]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1535],
         [ 0.7308],
         [-0.0520]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 2.1457],
         [

Sampling:  38%|███▊      | 384/1000 [00:04<00:05, 104.51it/s]

1 3
tensor([[[ 0.8369],
         [ 0.3829],
         [-1.2133]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0292],
         [ 0.7010],
         [ 0.3181]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6858],
         [ 2.0125],
         [ 2.3089]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2404],
         [ 1.0372],
         [ 0.6788]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6858],
         [ 2.0125],
         [ 2.3089]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 2.4001],
         [-0.9391],
         [ 3.0122]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.3970],
         [-0.2074],
         [ 0.7741]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.3388],
         [ 0.6957],
         [-0.2624]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2891],
         [-0.6982],
         [ 0.9395]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3813],
    

Sampling:  41%|████      | 406/1000 [00:04<00:05, 104.98it/s]

1 3
tensor([[[-1.5108],
         [ 2.3168],
         [ 0.5746]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.4126],
         [ 0.8145],
         [-1.5074]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.5910],
         [ 1.4709],
         [-1.7643]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5284],
         [ 2.1743],
         [-1.2300]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[1.2137],
         [0.6504],
         [0.3607]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.8241],
         [-0.5743],
         [-0.5452]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.0968],
         [ 0.8778],
         [-0.7393]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.4397],
         [ 0.1442],
         [-0.9287]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3825],
         [-0.2443],
         [ 0.9956]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.0518],
       

Sampling:  43%|████▎     | 428/1000 [00:04<00:05, 105.50it/s]

1 3
tensor([[[0.1329],
         [1.5156],
         [2.0408]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.7396],
         [ 0.7981],
         [-0.7387]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.3422],
         [-1.6202],
         [-0.9289]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.3880],
         [-0.2167],
         [-0.6777]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.9776],
         [0.8176],
         [0.1419]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6130],
         [ 1.1115],
         [-0.0304]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.9243],
         [0.7166],
         [0.9561]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2071],
         [-0.7922],
         [-0.9159]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.7272],
         [0.3664],
         [1.3286]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0395],
         [-0.769

Sampling:  45%|████▌     | 450/1000 [00:04<00:05, 104.43it/s]

1 3
tensor([[[-0.2014],
         [-0.1908],
         [-0.3908]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.9243],
         [0.7166],
         [0.9561]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.0861],
         [ 0.9066],
         [-0.2586]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1350],
         [-0.1441],
         [-0.6431]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9708],
         [ 0.0284],
         [ 1.1287]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.4584],
         [ 1.2057],
         [ 1.4358]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7555],
         [-0.1294],
         [-0.6929]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.7272],
         [0.3664],
         [1.3286]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.5836],
         [ 1.4688],
         [-0.2441]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1743],
         [

Sampling:  47%|████▋     | 472/1000 [00:04<00:05, 104.75it/s]

1 3
tensor([[[-0.9163],
         [-0.0092],
         [ 1.0460]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2427],
         [ 1.3152],
         [-0.5284]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7158],
         [ 0.9827],
         [-0.3362]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 2.2157],
         [ 0.8267],
         [-0.8209]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.8120],
         [ 1.4993],
         [ 0.7218]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1948],
         [-0.9916],
         [-1.3915]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.0643],
         [0.3261],
         [1.2184]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2653],
         [ 0.8834],
         [ 1.0643]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-2.0877],
         [ 1.5820],
         [ 1.0518]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[1.2057],
        

Sampling:  49%|████▉     | 494/1000 [00:05<00:04, 105.18it/s]

1 3
tensor([[[-0.1592],
         [ 0.6925],
         [ 2.2740]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5051],
         [-1.7396],
         [ 0.7981]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0133],
         [-0.8853],
         [-0.6009]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.2861],
         [ 1.5504],
         [-0.8491]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2142],
         [-0.4374],
         [-1.9525]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2624],
         [ 2.1457],
         [-0.2491]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.9066],
         [-0.2586],
         [ 0.1861]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4333],
         [-0.9401],
         [-0.5508]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4044],
         [-0.4714],
         [-0.6042]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.1902],
    

Sampling:  52%|█████▏    | 516/1000 [00:05<00:04, 104.78it/s]

tensor([[[ 0.2575],
         [-1.2462],
         [-2.1121]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.5477],
         [-0.2941],
         [ 0.7247]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.1902],
         [-0.4924],
         [-0.0381]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.2305],
         [-0.9293],
         [ 0.7158]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.0588],
         [-0.2142],
         [-0.4374]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.9427],
         [0.8556],
         [1.4839]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.8145],
         [ 1.7445],
         [ 0.8970]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.0309],
         [-1.8120],
         [ 1.4993]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.2085],
         [-1.6443],
         [-0.4009]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.2725],
         [1.

Sampling:  54%|█████▍    | 538/1000 [00:05<00:04, 104.08it/s]

1 3
tensor([[[ 1.3133],
         [ 0.2155],
         [-0.2247]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2891],
         [ 0.2518],
         [-0.7697]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.3904],
         [-0.6095],
         [-0.5371]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4340],
         [-1.7118],
         [-1.1665]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4049],
         [ 1.5802],
         [ 0.3388]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.1902],
         [-0.8588],
         [-0.0333]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2765],
         [ 0.1174],
         [ 1.5785]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6812],
         [-0.9633],
         [-1.2341]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3039],
         [-0.9020],
         [-1.1037]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.5491],
     

Sampling:  56%|█████▌    | 560/1000 [00:05<00:04, 102.53it/s]

1 3
tensor([[[-0.3908],
         [ 2.2964],
         [ 1.6422]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6760],
         [ 0.4420],
         [ 0.0655]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1103],
         [-1.2634],
         [-0.3340]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.5656],
         [-0.6392],
         [-0.4564]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6929],
         [ 1.4365],
         [ 0.7272]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6241],
         [-0.0846],
         [ 1.5960]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6288],
         [-0.1045],
         [ 0.5251]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.0447],
         [0.0491],
         [0.7187]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.9747],
         [-0.1184],
         [-0.9101]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9101],
       

Sampling:  58%|█████▊    | 582/1000 [00:05<00:04, 103.75it/s]

1 3
tensor([[[-1.7666],
         [-1.9562],
         [-0.9708]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.5495],
         [ 1.1865],
         [-1.3717]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.6614],
         [ 0.5687],
         [ 1.3676]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.0961],
         [0.5041],
         [1.0411]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5582],
         [-1.2189],
         [ 0.1525]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.4656],
         [ 0.7274],
         [-0.5375]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.8778],
         [-0.7393],
         [ 0.9031]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.1757],
         [-0.6505],
         [-0.6783]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2765],
         [ 0.1174],
         [ 1.5785]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7439],
       

Sampling:  60%|██████    | 604/1000 [00:06<00:03, 104.55it/s]

1 3
tensor([[[-0.2875],
         [ 0.0532],
         [ 0.5723]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.8958],
         [1.1105],
         [0.5296]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5661],
         [ 1.3133],
         [ 0.2155]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0962],
         [-0.6288],
         [-0.1045]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0381],
         [-1.3572],
         [-0.1539]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.1069],
         [1.4627],
         [1.0993]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.0921],
         [1.0709],
         [0.9596]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.2799],
         [ 2.4001],
         [-0.9391]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.6899],
         [-0.7970],
         [ 0.8503]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.1244],
         [-0.

Sampling:  63%|██████▎   | 626/1000 [00:06<00:03, 102.91it/s]

1 3
tensor([[[ 0.1135],
         [-0.5057],
         [-0.7709]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.6558],
         [1.0922],
         [2.1489]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.9628],
         [ 0.7775],
         [ 0.6059]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.1996],
         [-0.5582],
         [-1.2189]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7033],
         [-1.5436],
         [-1.8266]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3152],
         [ 1.9331],
         [-0.7657]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9535],
         [ 0.1609],
         [ 1.3059]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 2.3468],
         [-2.1713],
         [-0.1154]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.8961],
         [-0.7576],
         [ 0.2615]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.0613],
        

Sampling:  65%|██████▍   | 648/1000 [00:06<00:03, 103.63it/s]

1 3
tensor([[[-0.9284],
         [ 0.5215],
         [ 0.3381]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0307],
         [ 1.0232],
         [ 0.2305]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.5004],
         [-0.1384],
         [ 0.3378]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.7440],
         [0.2362],
         [0.6689]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.1521],
         [ 0.3284],
         [ 1.3472]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3725],
         [-0.6817],
         [ 0.3017]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.0252],
         [-0.2251],
         [-1.3254]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.7633],
         [ 0.7177],
         [-0.1500]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7705],
         [ 2.2398],
         [-0.0801]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.0788],
        

Sampling:  67%|██████▋   | 670/1000 [00:06<00:03, 104.34it/s]

1 3
tensor([[[-0.4137],
         [-0.6706],
         [ 0.1062]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.4250],
         [-0.6876],
         [-0.1743]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.9140],
         [ 1.4117],
         [-1.0215]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0962],
         [-0.6288],
         [-0.1045]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.2377],
         [1.1290],
         [0.3445]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.0015],
         [ 0.5960],
         [-0.0140]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2891],
         [ 0.2518],
         [-0.7697]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.9722],
         [-0.5084],
         [-0.6791]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.0851],
         [-0.5529],
         [-0.1592]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.0059],
       

Sampling:  69%|██████▉   | 692/1000 [00:07<00:02, 105.85it/s]

1 3
tensor([[[0.2500],
         [1.8074],
         [0.9747]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.1457],
         [-1.5741],
         [ 0.6011]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.5741],
         [ 0.6011],
         [ 0.7389]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.6641],
         [-0.4630],
         [ 0.1459]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-2.3029],
         [ 1.7046],
         [ 1.7478]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[1.2077],
         [0.1201],
         [0.2304]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.4250],
         [-0.6876],
         [-0.1743]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3572],
         [ 0.5456],
         [-1.8480]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5375],
         [ 0.5261],
         [ 0.7357]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1894],
         [

Sampling:  71%|███████▏  | 714/1000 [00:07<00:02, 104.28it/s]

1 3
tensor([[[-0.3287],
         [-1.1863],
         [ 0.6566]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.1902],
         [-0.4924],
         [-0.0381]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4414],
         [-0.6915],
         [-0.3846]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2443],
         [ 0.9427],
         [ 0.8556]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2086],
         [ 0.2121],
         [ 0.4838]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.9827],
         [-0.3362],
         [-1.8422]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0692],
         [ 1.4257],
         [ 0.3572]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.8328],
         [ 2.1723],
         [-2.0464]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4810],
         [-0.6931],
         [-0.2457]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.8958],
     

Sampling:  74%|███████▎  | 736/1000 [00:07<00:02, 105.55it/s]

1 3
tensor([[[-1.2385],
         [ 0.7619],
         [-1.4380]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.5741],
         [ 0.6011],
         [ 0.7389]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-2.3029],
         [ 1.7046],
         [ 1.7478]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.8145],
         [-1.5074],
         [-1.2713]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.3017],
         [1.9223],
         [0.3424]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.0539],
         [ 0.4605],
         [-0.5060]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.1820],
         [ 0.5768],
         [-0.4137]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3126],
         [-0.3989],
         [-0.9153]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.5452],
         [-0.0388],
         [-0.1737]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6858],
       

Sampling:  76%|███████▌  | 758/1000 [00:07<00:02, 106.46it/s]

1 3
tensor([[[-1.3717],
         [ 0.6641],
         [-0.4630]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.6757],
         [-0.3589],
         [-1.5451]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3519],
         [ 0.1069],
         [ 1.4627]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.1477],
         [-0.5147],
         [-1.1167]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7717],
         [ 0.1066],
         [ 0.8931]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7143],
         [-0.8241],
         [-0.5743]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3154],
         [ 1.6182],
         [-0.7501]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.5269],
         [ 1.1141],
         [-0.1013]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.1665],
         [ 0.3859],
         [ 0.3912]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2247],
    

Sampling:  77%|███████▋  | 769/1000 [00:07<00:02, 106.76it/s]

1 3
tensor([[[-0.1554],
         [-0.8434],
         [-0.8335]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[2.4163],
         [0.0146],
         [0.3808]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.6949],
         [-1.3920],
         [-0.6858]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-2.1383],
         [ 0.4637],
         [-0.7762]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.4903],
         [-0.4044],
         [-0.4714]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.4584],
         [ 1.2057],
         [ 1.4358]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.7482],
         [-0.2588],
         [ 1.3733]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3979],
         [-0.0408],
         [-0.1103]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2060],
         [-0.8951],
         [-1.5306]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7705],
       

Sampling:  79%|███████▉  | 791/1000 [00:07<00:01, 105.81it/s]

1 3
tensor([[[-0.1532],
         [-0.7110],
         [-1.1252]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9092],
         [-0.8153],
         [ 0.1431]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3774],
         [-0.0133],
         [-0.8853]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.9956],
         [ 0.9185],
         [-2.0318]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7069],
         [ 0.6331],
         [ 0.6249]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3500],
         [-1.3880],
         [-0.2167]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.5566],
         [0.6627],
         [1.1431]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3854],
         [-1.4364],
         [ 0.5910]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3225],
         [ 1.7402],
         [-0.2629]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9518],
       

Sampling:  81%|████████▏ | 813/1000 [00:08<00:01, 106.53it/s]

1 3
tensor([[[0.6566],
         [0.3152],
         [1.9331]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-2.0073e-01],
         [ 1.7182e-04],
         [-1.9535e-01]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 2.2398],
         [-0.0801],
         [-1.0770]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.5566],
         [0.6627],
         [1.1431]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1275],
         [-0.9121],
         [-1.3028]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4714],
         [-0.6042],
         [-1.2861]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7006],
         [-2.2612],
         [-0.1535]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4333],
         [-0.9401],
         [-0.5508]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[1.1268],
         [0.2774],
         [1.3388]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.5324],
  

Sampling:  84%|████████▎ | 835/1000 [00:08<00:01, 105.64it/s]

1 3
tensor([[[-0.7069],
         [ 0.6331],
         [ 0.6249]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.5130],
         [-0.3755],
         [-1.4228]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.3468],
         [ 0.3896],
         [-0.2867]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.4062],
         [0.4920],
         [1.7490]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6420],
         [-0.1736],
         [-0.6936]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9807],
         [ 0.3166],
         [-0.8398]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7970],
         [ 0.8503],
         [ 0.3614]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.1766],
         [-0.4109],
         [ 0.5894]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.5952],
         [-0.2208],
         [-0.2643]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.6788],
        

Sampling:  86%|████████▌ | 857/1000 [00:08<00:01, 104.54it/s]

1 3
tensor([[[-0.2236],
         [ 0.1405],
         [ 1.2085]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.3970],
         [-0.2074],
         [ 0.7741]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-2.4704],
         [-0.4971],
         [ 0.0506]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9153],
         [-0.1640],
         [-0.6760]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7697],
         [-0.5661],
         [ 1.3133]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7576],
         [ 0.2615],
         [ 0.2690]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.0968],
         [ 0.8778],
         [-0.7393]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.9799],
         [-1.1575],
         [ 1.1262]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7348],
         [ 1.0059],
         [-0.7554]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0133],
    

Sampling:  88%|████████▊ | 879/1000 [00:08<00:01, 105.12it/s]

1 3
tensor([[[ 0.8145],
         [-1.5074],
         [-1.2713]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7351],
         [-1.5108],
         [ 2.3168]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.8931],
         [ 0.3408],
         [-0.3116]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6313],
         [ 0.8958],
         [ 1.1105]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.1287],
         [ 0.1206],
         [-2.0877]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2156],
         [-0.9535],
         [ 0.1609]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-2.0847],
         [-0.5036],
         [-0.8424]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.7440],
         [0.2362],
         [0.6689]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0689],
         [-0.5547],
         [-2.0424]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.2653],
       

Sampling:  90%|█████████ | 901/1000 [00:09<00:00, 105.15it/s]

1 3
tensor([[[1.1268],
         [0.2774],
         [1.3388]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7609],
         [ 0.9590],
         [-1.3792]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6982],
         [ 0.9395],
         [-0.0625]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.5130],
         [-0.3755],
         [-1.4228]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[2.3089],
         [0.9029],
         [0.7669]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.1407],
         [ 0.4011],
         [-0.8997]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.4676],
         [-0.3909],
         [ 0.0961]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4009],
         [-1.2787],
         [ 2.3468]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.6746],
         [-0.9722],
         [-1.2385]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.2688],
         [0

Sampling:  93%|█████████▎| 934/1000 [00:09<00:00, 106.27it/s]

1 3
tensor([[[-0.3657],
         [-1.9138],
         [-0.8383]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.1135],
         [-0.5057],
         [-0.7709]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1082],
         [-1.4134],
         [ 0.8956]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3688],
         [-1.6380],
         [-1.2410]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.9024],
         [ 1.5697],
         [-1.1943]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[2.2964],
         [1.6422],
         [0.7905]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.1370],
         [-0.4373],
         [-2.2221]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.5251],
         [-0.4009],
         [-1.2787]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.8556],
         [ 1.4839],
         [-0.8086]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.4491],
       

Sampling:  94%|█████████▍| 945/1000 [00:09<00:00, 105.08it/s]

1 3
tensor([[[-0.6822],
         [ 1.4264],
         [ 0.2100]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1103],
         [-1.2634],
         [-0.3340]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.7717],
         [ 0.1066],
         [ 0.8931]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.3162],
         [-0.4596],
         [-1.3295]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4044],
         [-0.4714],
         [-0.6042]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6915],
         [-0.3846],
         [ 0.1329]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6783],
         [ 1.5479],
         [-0.5144]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0317],
         [ 0.2499],
         [-1.7072]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.3286],
         [-0.7905],
         [-0.5524]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6969],
    

Sampling:  97%|█████████▋| 967/1000 [00:09<00:00, 104.19it/s]

1 3
tensor([[[-0.8951],
         [-1.5306],
         [ 0.3093]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.8970],
         [-0.8812],
         [ 1.4993]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.7247],
         [-0.3774],
         [-0.0133]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.6788],
         [0.9002],
         [0.5207]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.4374],
         [-1.9525],
         [-1.4407]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.8469],
         [ 1.4491],
         [-0.1383]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-1.0441],
         [ 0.7888],
         [ 1.5130]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-2.0877],
         [ 1.5820],
         [ 1.0518]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[0.0942],
         [0.2017],
         [2.1184]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.6777],
         [

Sampling:  99%|█████████▉| 989/1000 [00:09<00:00, 105.84it/s]

1 3
tensor([[[ 0.1193],
         [-0.2284],
         [-0.7976]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1749],
         [ 1.0801],
         [ 1.0493]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.3688],
         [-1.6380],
         [-1.2410]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.8241],
         [-0.5743],
         [-0.5452]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.5960],
         [ 0.6561],
         [-0.6091]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.0493],
         [ 2.1888],
         [-0.3082]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 0.4605],
         [-0.5060],
         [-0.9959]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.0689],
         [-0.5547],
         [-2.0424]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[-0.1441],
         [-0.6431],
         [ 0.2882]]], device='cuda:0')
torch.Size([1, 3, 1])
10
1 3
tensor([[[ 1.1133],
    

Mean values over 10,000 samples:
0    1.002111
dtype: float32

Standard deviations over 10,000 samples:
0    0.039305
dtype: float32


In [2]:
#TRAIN:
import train
import argparse

parser = argparse.ArgumentParser()
# Meta parameters
parser.add_argument('-base_dir', default='./numerical_results', type=str)
parser.add_argument('-use_cuda', type=bool, default=True)
# Specify the GPU to use
parser.add_argument('-device', default=0, type=int)
# For retraining, increase number of seeds
parser.add_argument('-num_seeds', default=1, type=int)
parser.add_argument('-initial_seed', default=5, type=int)
parser.add_argument('-datasets', default=['correlated_Blackscholes'], nargs="+")  #'correlated_Blackscholes', 'Heston', 'YFinance'
parser.add_argument('-algos', default=['SigCWGAN'], nargs="+")  # 'GMMN', 'RCGAN', 'TimeGAN', 'CWGAN', 'RCWGAN'

# Algo hyperparameters
parser.add_argument('-batch_size', default=200, type=int)
parser.add_argument('-p', default=3, type=int)
parser.add_argument('-q', default=3, type=int)
parser.add_argument('-hidden_dims', default=3 * (50,), type=tuple)
parser.add_argument('-total_steps', default=10000, type=int)
#parser.add_argument('-mc_samples', default=1000, type=int)
parser.add_argument('-window_size', default=6250, type=int)
parser.add_argument('-grid_points', default=1, type=int)
parser.add_argument('-num_paths', default=1, type=int)
parser.add_argument('-num_bm', default=1, type=int)

# Ignore unknown arguments
args, unknown = parser.parse_known_args()
train.main(args)

Start of training. CUDA: True
Executing: SigCWGAN, YFinance, ticker=^GSPC_start=2000-01-01_end=2025-01-01_q=10
YF.download() has changed argument auto_adjust default to True


YFinance Dataset includes this many days (not only trading days): 1 6289
[[1.         0.96165533 0.96350381 ... 4.10304969 4.05913887 4.04174627]]
This has drift: 7.168025343341337e+152


100%|█████████████████████████████████████| 10000/10000 [12:59<00:00, 12.83it/s]


In [ ]:
#TRAIN:
import train
import argparse

parser = argparse.ArgumentParser()
# Meta parameters
parser.add_argument('-base_dir', default='./numerical_results', type=str)
parser.add_argument('-use_cuda', type=bool, default=True)
# Specify the GPU to use
parser.add_argument('-device', default=0, type=int)
# For retraining, increase number of seeds
parser.add_argument('-num_seeds', default=1, type=int)
parser.add_argument('-initial_seed', default=9, type=int)
parser.add_argument('-datasets', default=['Heston'], nargs="+")  #'correlated_Blackscholes', 'Heston', 'YFinance'
parser.add_argument('-algos', default=['SigCWGAN'], nargs="+")  # 'GMMN', 'RCGAN', 'TimeGAN', 'CWGAN', 'RCWGAN'

# Algo hyperparameters
parser.add_argument('-batch_size', default=200, type=int)
parser.add_argument('-p', default=3, type=int)
parser.add_argument('-q', default=10, type=int)
parser.add_argument('-hidden_dims', default=3 * (50,), type=tuple)
parser.add_argument('-total_steps', default=10000, type=int)
#parser.add_argument('-mc_samples', default=1000, type=int)
parser.add_argument('-window_size', default=6250, type=int)
parser.add_argument('-grid_points', default=252, type=int)
parser.add_argument('-num_paths', default=1, type=int)
parser.add_argument('-num_bm', default=1, type=int)

# Ignore unknown arguments
args, unknown = parser.parse_known_args()
train.main(args)

Start of training. CUDA: True
Executing: SigCWGAN, Heston, mu=1_sigma=0.04_q=10
[[1.         1.00025055 0.98654684 ... 3.84975342 3.95086073 3.92127244]]
This has drift: 1.056639829893056


 95%|████████████████████████████████████▏ | 9533/10000 [12:23<00:36, 12.86it/s]

In [3]:
#EVALUATE:
import evaluate
import argparse

parser = argparse.ArgumentParser(description='Turn cuda off / on during evaluation.')
parser.add_argument('-base_dir', default='./numerical_results/', type=str)
# Set to False if evaluation should be done on CPU
parser.add_argument('-use_cuda', default=True, type=bool)
# Specify the GPU to use (0 if only one is available)
parser.add_argument('-device', default=0, type=int)
parser.add_argument('-datasets', default=['correlated_Blackscholes',# "YFinance"
], nargs="+")
parser.add_argument('-algos', default=['SigCWGAN',], nargs="+") #'CWGAN', 'GMMN', 'RCGAN', 'TimeGAN', 

# Ignore unknown arguments
args, unknown = parser.parse_known_args()
evaluate.evaluate_benchmarks(base_dir=args.base_dir, use_cuda=args.use_cuda, datasets=args.datasets, algos=args.algos)


Running evalution on GPU.
   ./numerical_results/correlated_Blackscholes/mu=[0.06]_sigma=[[0.4472136]]_q=10/seed=42/SigCWGAN
Saving summary to ./numerical_results/correlated_Blackscholes/mu=[0.06]_sigma=[[0.4472136]]_q=10/summary.csv ...
